# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b74ed3698a8b33aab1df14744e55696adeb223b04826e4eb0d388499e5e165136562dfc1245d81ad04b22d2bfcc9696f59228faad4ee666180cb92f7f0e2b6b

test:
  secret_key_base: 90a9868aa7eb87cb570cc33f169e1fae8dab008390cb6c2eaf4fef5b4a275977a8eba9be7e3822a096e0214760ddeaf8701378b3f029d35c3d08e1f31e0eda19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
